# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-01 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='inputFile',
            field=models.CharField(default='', max_length=100),
        ),
    ]
